#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "diagnostickoeur"
name = "DiagnoStickœur"

maintainers = ["Tagada"]

description.en = "Print sticker labels!"
description.fr = "Imprimer des stickers !"

version = "0.2025.03.13~ynh1"

[upstream]
license = "GPL-3.0-or-later"

code = "https://framagit.org/stickoeur/diagnostickoeur"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all" 
multi_instance = false
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.sources.main]
    url = "https://framagit.org/Tagadda/diagnostickoeur/-/archive/e5ea8e213e00a53cb2a119d506d10e8d855a8eba/diagnostickoeur-e5ea8e213e00a53cb2a119d506d10e8d855a8eba.tar.gz"
    sha256 = "e2181bb4e24fbbddf72753b3c7718a3b39e8f47f99ebeda4bb67a976606e5fed"

    autoupdate.strategy = "latest_gitlab_commit"

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "python3, python3-pip, python3-venv"
