#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "diagnostickoeur"
name = "DiagnoStickœur"

maintainers = ["Tagada"]

description.en = "Print sticker labels!"
description.fr = "Imprimer des stickers !"

version = "2025.08.19~ynh1"

[upstream]
license = "GPL-3.0-or-later"

code = "https://framagit.org/stickoeur/diagnostickoeur"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = false

ldap = "not_relevant"

sso = "not_relevant"

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources.main]
    url = "https://framagit.org/stickoeur/diagnostickoeur/-/archive/a19400c58a9d8c30339b5c33d47dbe5525a5c6e5/diagnostickoeur-a19400c58a9d8c30339b5c33d47dbe5525a5c6e5.tar.bz2"
    sha256 = "fc8ee2372e8053c56330bbc8d80d58b99feaa4f32ab7e45654ebfe93d25bf4ab"

    autoupdate.strategy = "latest_gitlab_commit"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = "python3, python3-pip, python3-venv"
